name: Build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
            ${{github.workspace}}/build/vega_main
            ${{github.workspace}}/build/vega_test
            ${{github.workspace}}/build/vega_benchmark

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries
        
    - run: chmod +x ${{github.workspace}}/vega_test

    - name: Test
      run: ${{github.workspace}}/vega_test

  benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries

    - run: chmod +x ${{github.workspace}}/vega_benchmark

    - name: Benchmark
      run: ${{github.workspace}}/vega_benchmark
