name: Build and Test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build

  test:
    runs-on: ubuntu-latest
    
    needs: build

    steps:
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest 
