name: Build and Test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          build/vega_main
          buid/vega_test
    - name: Configure CMake
      run: cmake -B build ..
    
    - name: Build
      run: cmake --build build

  test:
    runs-on: ubuntu-latest
    
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries
    - name: Test
      working-directory: build
      run: chmod +x vega_test && ./vega_test